//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpeedClientDbContext : DbContext
    {
        public SpeedClientDbContext()
            : base("name=SpeedClientDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AIBoxCamera> AIBoxCameras { get; set; }
        public DbSet<AIBoxHistory> AIBoxHistorys { get; set; }
        public DbSet<AIBoxServer> AIBoxServers { get; set; }
        public DbSet<CampaignCode> CampaignCodes { get; set; }
        public DbSet<CampaignCodeTransaction> CampaignCodeTransactions { get; set; }
        public DbSet<CampaignGroup> CampaignGroups { get; set; }
        public DbSet<CampaignMemberGroupLink> CampaignMemberGroupLinks { get; set; }
        public DbSet<Campaign> Campaigns { get; set; }
        public DbSet<CampaignStoreLink> CampaignStoreLinks { get; set; }
        public DbSet<EmployeeFunctionLink> EmployeeFunctionLinks { get; set; }
        public DbSet<EmployeeGroup> EmployeeGroups { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmployeeStoreLink> EmployeeStoreLinks { get; set; }
        public DbSet<Function> Functions { get; set; }
        public DbSet<MemberAIBoxLink> MemberAIBoxLinks { get; set; }
        public DbSet<MemberCode> MemberCodes { get; set; }
        public DbSet<MemberDelivery> MemberDeliverys { get; set; }
        public DbSet<MemberGroup> MemberGroups { get; set; }
        public DbSet<MemberPointLink> MemberPointLinks { get; set; }
        public DbSet<MemberPointTransaction> MemberPointTransactions { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<MemberWalletLink> MemberWalletLinks { get; set; }
        public DbSet<MemberWalletTransaction> MemberWalletTransactions { get; set; }
        public DbSet<Point> Points { get; set; }
        public DbSet<Reservation> Reservations { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<Wallet> Wallets { get; set; }
    }
}
